// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD1ea2e5DecodeGithubComIamStubborNPetstoreDbModels(in *jlexer.Lexer, out *InvoiceItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "user_name":
			out.User = string(in.String())
		case "pet":
			out.Pet = string(in.String())
		case "category":
			out.Category = string(in.String())
		case "ship_date":
			out.ShipDate = string(in.String())
		case "quantity":
			out.Quantity = int32(in.Int32())
		case "price":
			out.Price = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1ea2e5EncodeGithubComIamStubborNPetstoreDbModels(out *jwriter.Writer, in InvoiceItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"user_name\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	{
		const prefix string = ",\"pet\":"
		out.RawString(prefix)
		out.String(string(in.Pet))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"ship_date\":"
		out.RawString(prefix)
		out.String(string(in.ShipDate))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int32(int32(in.Quantity))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InvoiceItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1ea2e5EncodeGithubComIamStubborNPetstoreDbModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InvoiceItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1ea2e5EncodeGithubComIamStubborNPetstoreDbModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InvoiceItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1ea2e5DecodeGithubComIamStubborNPetstoreDbModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InvoiceItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1ea2e5DecodeGithubComIamStubborNPetstoreDbModels(l, v)
}
